name: Hello World

on: schedule
  schedule: 
    - cron: "0 0 * * *"
jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Greeting
        run: echo "Hello, I am your first GitHub Action!"
